# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_trainWindow(object):
    def setupUi(self, trainWindow):
        trainWindow.setObjectName("trainWindow")
        trainWindow.resize(1045, 743)
        trainWindow.setStyleSheet("#centralwidget {\n"
"    background: white;\n"
"}\n"
"\n"
" /* Boton para vilver al inicio */\n"
"#openIndexWindow {\n"
"    font-size: 16pt;\n"
"    background: whitesmoke;\n"
"    border-radius: 15px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#openIndexWindow:hover {\n"
"    color: white;\n"
"    width: 20px;\n"
"    background-color: blue;\n"
"}\n"
"\n"
"/* Boton para abrir dialogo de configuracion de entrenamiento */\n"
"#openTrainingConfig {\n"
"    font-size: 12pt;\n"
"    background: whitesmoke;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#openTrainingConfig:hover {\n"
"    background: white;\n"
"    border: 2px solid blue;\n"
"}\n"
"\n"
"/* Boton para comenzar entrenamiento */\n"
"#startTraining {\n"
"    font-size: 12pt;\n"
"    background: whitesmoke;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#startTraining:hover {\n"
"    background: green;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Boton para detener entrenamiento */\n"
"#stopTraining {\n"
"    font-size: 12pt;\n"
"    background: whitesmoke;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"#stopTraining:hover {\n"
"    background: red;\n"
"    color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(trainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lossGraph = PlotWidget(self.centralwidget)
        self.lossGraph.setMinimumSize(QtCore.QSize(400, 300))
        self.lossGraph.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lossGraph.setObjectName("lossGraph")
        self.horizontalLayout_7.addWidget(self.lossGraph)
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.accuracyGraph = PlotWidget(self.centralwidget)
        self.accuracyGraph.setMinimumSize(QtCore.QSize(400, 300))
        self.accuracyGraph.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.accuracyGraph.setObjectName("accuracyGraph")
        self.horizontalLayout_7.addWidget(self.accuracyGraph)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lossDisp = QtWidgets.QLabel(self.centralwidget)
        self.lossDisp.setMinimumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lossDisp.setFont(font)
        self.lossDisp.setObjectName("lossDisp")
        self.horizontalLayout_6.addWidget(self.lossDisp)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.accuracyDisp = QtWidgets.QLabel(self.centralwidget)
        self.accuracyDisp.setMinimumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.accuracyDisp.setFont(font)
        self.accuracyDisp.setObjectName("accuracyDisp")
        self.horizontalLayout_6.addWidget(self.accuracyDisp)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.testDisp = QtWidgets.QLabel(self.centralwidget)
        self.testDisp.setMinimumSize(QtCore.QSize(500, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.testDisp.setFont(font)
        self.testDisp.setAlignment(QtCore.Qt.AlignCenter)
        self.testDisp.setObjectName("testDisp")
        self.verticalLayout_7.addWidget(self.testDisp)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.epochLabel = QtWidgets.QLabel(self.centralwidget)
        self.epochLabel.setMinimumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.epochLabel.setFont(font)
        self.epochLabel.setObjectName("epochLabel")
        self.verticalLayout_6.addWidget(self.epochLabel)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.trainProgress = QtWidgets.QProgressBar(self.centralwidget)
        self.trainProgress.setMinimumSize(QtCore.QSize(0, 0))
        self.trainProgress.setProperty("value", 24)
        self.trainProgress.setObjectName("trainProgress")
        self.verticalLayout_5.addWidget(self.trainProgress)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.openTrainingConfig = QtWidgets.QPushButton(self.centralwidget)
        self.openTrainingConfig.setMinimumSize(QtCore.QSize(140, 40))
        self.openTrainingConfig.setMaximumSize(QtCore.QSize(140, 40))
        self.openTrainingConfig.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.openTrainingConfig.setObjectName("openTrainingConfig")
        self.horizontalLayout_5.addWidget(self.openTrainingConfig)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.stopTraining = QtWidgets.QPushButton(self.centralwidget)
        self.stopTraining.setMinimumSize(QtCore.QSize(140, 40))
        self.stopTraining.setMaximumSize(QtCore.QSize(140, 40))
        self.stopTraining.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopTraining.setObjectName("stopTraining")
        self.horizontalLayout_5.addWidget(self.stopTraining)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.startTraining = QtWidgets.QPushButton(self.centralwidget)
        self.startTraining.setMinimumSize(QtCore.QSize(140, 40))
        self.startTraining.setMaximumSize(QtCore.QSize(140, 40))
        self.startTraining.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startTraining.setObjectName("startTraining")
        self.horizontalLayout_5.addWidget(self.startTraining)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.openIndexWindow = QtWidgets.QPushButton(self.centralwidget)
        self.openIndexWindow.setMinimumSize(QtCore.QSize(140, 50))
        self.openIndexWindow.setMaximumSize(QtCore.QSize(140, 50))
        self.openIndexWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/house.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.openIndexWindow.setIcon(icon)
        self.openIndexWindow.setIconSize(QtCore.QSize(40, 40))
        self.openIndexWindow.setObjectName("openIndexWindow")
        self.verticalLayout_10.addWidget(self.openIndexWindow)
        self.gridLayout_2.addLayout(self.verticalLayout_10, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 2, 1, 1, 1)
        trainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(trainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 25))
        self.menubar.setObjectName("menubar")
        trainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(trainWindow)
        self.statusbar.setObjectName("statusbar")
        trainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(trainWindow)
        QtCore.QMetaObject.connectSlotsByName(trainWindow)

    def retranslateUi(self, trainWindow):
        _translate = QtCore.QCoreApplication.translate
        trainWindow.setWindowTitle(_translate("trainWindow", "MainWindow"))
        self.lossDisp.setText(_translate("trainWindow", "Costo de entrenamiento:"))
        self.accuracyDisp.setText(_translate("trainWindow", "Exactitud de entrenamiento:"))
        self.testDisp.setText(_translate("trainWindow", "Costo de prueba: - Exactitud de prueba:"))
        self.epochLabel.setText(_translate("trainWindow", "Epoch"))
        self.openTrainingConfig.setText(_translate("trainWindow", "Configuración"))
        self.stopTraining.setText(_translate("trainWindow", "Detener"))
        self.startTraining.setText(_translate("trainWindow", "Entrenar"))
        self.openIndexWindow.setText(_translate("trainWindow", "Inicio"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trainWindow = QtWidgets.QMainWindow()
    ui = Ui_trainWindow()
    ui.setupUi(trainWindow)
    trainWindow.show()
    sys.exit(app.exec_())
